import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.scss';

import { Avatar, Header, Nav, ContactData } from '@/components';

const notoSans = Noto_Sans({
	variable: '--font-noto-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Francisco Arleo - Resume',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${notoSans.variable} antialiased overflow-hidden w-full flex flex-col lg:pt-16`}>
				<div className='flex max-w-[700px]  w-full lg:mx-auto shadow-lg h-[calc(100vh-4rem)]'>
					<Nav />
					<div className='col-2 bg-white p-8 max-h-full overflow-y-auto'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
