import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.scss';

import { Avatar, Header, Nav, ContactData } from '@/components';

const notoSans = Noto_Sans({
	variable: '--font-noto-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Francisco Arleo - Resume',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const mouse = (
		<div className='absolute top-[50%] right-[2%] w-[25%] rotate-[-33deg]'>
			<img
				src='img/mouseMockup.png'
				className='drop-shadow-[-21px_24px_17px_rgba(0,0,0,0.25)]'
			/>
		</div>
	);
	return (
		<html lang='en'>
			<body
				className={`${notoSans.variable} antialiased overflow-hidden w-full flex flex-col lg:pt-16`}>
				<div className='flex max-w-[700px]  w-full lg:mx-auto shadow-lg h-[calc(100vh-4rem)]'>
					<Nav />
					<div className='col-2 bg-white p-8 max-h-full overflow-y-auto'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
