import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';

import { Avatar, Header, Nav, ContactData } from '@/components';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Francisco Arleo - Resume',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden w-full h-full flex flex-col`}>
				<div className='grid grid-cols-[200px_1fr]  grow max-w-[800px] w-full lg:mx-auto lg:p-16'>
					<Nav />
					<div className='border-4 border-warning col-2'>{children}</div>
				</div>
			</body>
		</html>
	);
}
